items:
  sla:
   material: "OAK_HANGING_SIGN"
   displayName: "ยง6teste"
   lore:
     - " "
     - "ยง7teste"
     - " "
     -
  sla2:
    material: "ACACIA_HANGING_SIGN"
    displayName: "ยง6teste2"
    lore:
      - " "
      - "ยง7teste2"
      - " "